### ISSUE TITLE
RDFByModularityClustering should be able to write to HDFS

### ISSUE THREAD

**Issue by earthquakesan** [SANSA-Stack/SANSA-Examples#11]
This example fails:
```
import scala.collection.mutable
import org.apache.spark.sql.SparkSession
import org.apache.log4j.{ Level, Logger }
import net.sansa_stack.ml.spark.clustering.RDFByModularityClustering

val graphFile = "hdfs://namenode:8020/data/Clustering_sampledata.nt"
val outputFile = "hdfs://namenode:8020/data/clustering.out"
val numIterations = 10

RDFByModularityClustering(sc, numIterations, graphFile, outputFile)
```
The stacktrace is:
```
import scala.collection.mutable
import org.apache.spark.sql.SparkSession
import org.apache.log4j.{Level, Logger}
import net.sansa_stack.ml.spark.clustering.RDFByModularityClustering
graphFile: String = hdfs://namenode:8020/data/Clustering_sampledata.nt
outputFile: String = hdfs://namenode:8020/data/clustering.out
numIterations: Int = 10
The number of nodes in the knowledge graph is 8 and the number of edges is 13.
The first ten edges of the graph look like the following: 
(<http://twitter/user0>,<http://twitter/user1>)
(<http://twitter/user0>,<http://twitter/user2>)
(<http://twitter/user0>,<http://twitter/user3>)
(<http://twitter/user1>,<http://twitter/user2>)
(<http://twitter/user1>,<http://twitter/user3>)
(<http://twitter/user1>,<http://twitter/user6>)
(<http://twitter/user2>,<http://twitter/user3>)
(<http://twitter/user3>,<http://twitter/user4>)
(<http://twitter/user4>,<http://twitter/user5>)
(<http://twitter/user5>,<http://twitter/user6>)
Starting iteration
1
2
3
4
5
6
7
java.io.FileNotFoundException: hdfs:/namenode:8020/data/clustering.out (No such file or directory)
  at java.io.FileOutputStream.open0(Native Method)
  at java.io.FileOutputStream.open(FileOutputStream.java:270)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
  at java.io.PrintWriter.<init>(PrintWriter.java:263)
  at net.sansa_stack.ml.spark.clustering.RDFByModularityClustering$.apply(RDFByModularityClustering.scala:97)
  ... 52 elided
```

**Comment by gezims** [comment]
Based on this commit (https://github.com/SANSA-Stack/SANSA-ML/commit/0ebe86ba36a229d801eddecc8c7dfc83cdd808ea ) will print out and write output tile into HDFS/local file.
