### ISSUE TITLE
Spark query example fails because of missing jetty XmlParser

### ISSUE THREAD

**Issue by thomasrebele** [SANSA-Stack/SANSA-Examples#19]
I followd the instructions [running on spark](https://github.com/SANSA-Stack/SANSA-Examples/tree/develop/sansa-examples-spark#running-the-application-on-a-spark-standalone-cluster), using the following command

```
../spark-2.1.1-bin-hadoop2.7/bin/spark-submit  --class net.sansa_stack.examples.spark.query.Sparklify --master spark://spark-master:7077 target/sansa-examples-spark_2.11-2017-06.1-SNAPSHOT.jar ~/all.ntriples
```

The execution fails because of a NoClassDefFoundError:

```
17/10/28 17:49:17 INFO WebInfConfiguration: Extract jar:file:/home/tr/sansa-examples/sansa-examples-spark/target/sansa-examples-spark_2.11-2017-06.1-SNAPSHOT.jar!/ to /tmp/jetty-0.0.0.0-7531-sansa-examples-spark_2.11-2017-06.1-SNAPSHOT.jar-_-any-/webapp
17/10/28 17:49:23 WARN AbstractLifeCycle: FAILED o.e.j.w.WebAppContext{/,file:/tmp/jetty-0.0.0.0-7531-sansa-examples-spark_2.11-2017-06.1-SNAPSHOT.jar-_-any-/webapp/},file:/home/tr/sansa-examples/sansa-examples-spark/target/sansa-examples-spark_2.11-2017-06.1-SNAPSHOT.jar: java.lang.NoClassDefFoundError: org/eclipse/jetty/xml/XmlParser
java.lang.NoClassDefFoundError: org/eclipse/jetty/xml/XmlParser
	at org.eclipse.jetty.webapp.WebDescriptor.newParser(WebDescriptor.java:70)
	at org.eclipse.jetty.webapp.WebDescriptor.ensureParser(WebDescriptor.java:61)
	at org.eclipse.jetty.webapp.Descriptor.parse(Descriptor.java:59)
	at org.eclipse.jetty.webapp.WebDescriptor.parse(WebDescriptor.java:148)
	at org.eclipse.jetty.webapp.MetaData.setDefaults(MetaData.java:149)
	at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:54)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:457)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.aksw.jena_sparql_api.web.server.ServerUtils.startServer(ServerUtils.java:56)
	at org.aksw.jena_sparql_api.web.server.ServerUtils.startServer(ServerUtils.java:48)
	at org.aksw.jena_sparql_api.web.server.ServerUtils.startServer(ServerUtils.java:40)
	at org.aksw.jena_sparql_api.server.utils.FactoryBeanSparqlServer.create(FactoryBeanSparqlServer.java:84)
	at net.sansa_stack.examples.spark.query.Sparklify$.main(Sparklify.scala:60)
	at net.sansa_stack.examples.spark.query.Sparklify.main(Sparklify.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.xml.XmlParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
```
Is there any easy way to fix it?

**Comment by SimonBin** [comment]
can you try if this is fixed by https://github.com/SANSA-Stack/SANSA-Examples/commit/7049662750cddaa29b6d7700c3e6aa28ffc1d222

**Comment by patrickwestphal** [comment]
Seems to be solved. Thanks @SimonBin !
