### ISSUE TITLE
query.Sparklify example fails (NullPointer exception)

### ISSUE THREAD

**Issue by earthquakesan** [SANSA-Stack/SANSA-Examples#6]
```
app_1  | 17/05/09 13:49:32 INFO rdd.HadoopRDD: Input split: file:/rdf/rdf.nt:0+8392
app_1  | 17/05/09 13:49:32 INFO rdd.HadoopRDD: Input split: file:/rdf/rdf.nt:8392+8392
app_1  | 17/05/09 13:49:32 INFO Configuration.deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
app_1  | 17/05/09 13:49:32 INFO Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
app_1  | 17/05/09 13:49:32 INFO Configuration.deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
app_1  | 17/05/09 13:49:32 INFO Configuration.deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
app_1  | 17/05/09 13:49:32 INFO Configuration.deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
app_1  | 17/05/09 13:49:32 ERROR executor.Executor: Exception in task 0.0 in stage 0.0 (TID 0)
app_1  | java.lang.ExceptionInInitializerError
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:27)
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:26)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
app_1  | 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
app_1  | 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
app_1  | 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at java.lang.Thread.run(Thread.java:745)
app_1  | Caused by: java.lang.NullPointerException
app_1  | 	at org.apache.jena.tdb.sys.EnvTDB.processGlobalSystemProperties(EnvTDB.java:33)
app_1  | 	at org.apache.jena.tdb.TDB.init(TDB.java:248)
app_1  | 	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
app_1  | 	at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
app_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:163)
app_1  | 	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:109)
app_1  | 	at org.apache.jena.riot.RDFDataMgr.<clinit>(RDFDataMgr.java:81)
app_1  | 	... 14 more
app_1  | 17/05/09 13:49:32 ERROR executor.Executor: Exception in task 1.0 in stage 0.0 (TID 1)
app_1  | java.lang.NoClassDefFoundError: Could not initialize class org.apache.jena.riot.RDFDataMgr
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:27)
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:26)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
app_1  | 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
app_1  | 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
app_1  | 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at java.lang.Thread.run(Thread.java:745)
app_1  | 17/05/09 13:49:32 WARN scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.ExceptionInInitializerError
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:27)
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:26)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
app_1  | 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
app_1  | 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
app_1  | 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at java.lang.Thread.run(Thread.java:745)
app_1  | Caused by: java.lang.NullPointerException
app_1  | 	at org.apache.jena.tdb.sys.EnvTDB.processGlobalSystemProperties(EnvTDB.java:33)
app_1  | 	at org.apache.jena.tdb.TDB.init(TDB.java:248)
app_1  | 	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
app_1  | 	at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
app_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:163)
app_1  | 	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:109)
app_1  | 	at org.apache.jena.riot.RDFDataMgr.<clinit>(RDFDataMgr.java:81)
app_1  | 	... 14 more
app_1  | 
app_1  | 17/05/09 13:49:32 ERROR scheduler.TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
app_1  | 17/05/09 13:49:32 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
app_1  | 17/05/09 13:49:32 WARN scheduler.TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1, localhost, executor driver): java.lang.NoClassDefFoundError: Could not initialize class org.apache.jena.riot.RDFDataMgr
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:27)
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:26)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
app_1  | 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
app_1  | 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
app_1  | 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at java.lang.Thread.run(Thread.java:745)
app_1  | 
app_1  | 17/05/09 13:49:32 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
app_1  | 17/05/09 13:49:32 INFO scheduler.TaskSchedulerImpl: Cancelling stage 0
app_1  | 17/05/09 13:49:32 INFO scheduler.DAGScheduler: ShuffleMapStage 0 (distinct at RdfPartitionUtilsSpark.scala:22) failed in 0.834 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.ExceptionInInitializerError
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:27)
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:26)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
app_1  | 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
app_1  | 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
app_1  | 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at java.lang.Thread.run(Thread.java:745)
app_1  | Caused by: java.lang.NullPointerException
app_1  | 	at org.apache.jena.tdb.sys.EnvTDB.processGlobalSystemProperties(EnvTDB.java:33)
app_1  | 	at org.apache.jena.tdb.TDB.init(TDB.java:248)
app_1  | 	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
app_1  | 	at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
app_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:163)
app_1  | 	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:109)
app_1  | 	at org.apache.jena.riot.RDFDataMgr.<clinit>(RDFDataMgr.java:81)
app_1  | 	... 14 more
app_1  | 
app_1  | Driver stacktrace:
app_1  | 17/05/09 13:49:32 INFO scheduler.DAGScheduler: Job 0 failed: collect at RdfPartitionUtilsSpark.scala:22, took 0.939503 s
app_1  | Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.lang.ExceptionInInitializerError
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:27)
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:26)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
app_1  | 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
app_1  | 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
app_1  | 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at java.lang.Thread.run(Thread.java:745)
app_1  | Caused by: java.lang.NullPointerException
app_1  | 	at org.apache.jena.tdb.sys.EnvTDB.processGlobalSystemProperties(EnvTDB.java:33)
app_1  | 	at org.apache.jena.tdb.TDB.init(TDB.java:248)
app_1  | 	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
app_1  | 	at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
app_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:163)
app_1  | 	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:109)
app_1  | 	at org.apache.jena.riot.RDFDataMgr.<clinit>(RDFDataMgr.java:81)
app_1  | 	... 14 more
app_1  | 
app_1  | Driver stacktrace:
app_1  | 	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
app_1  | 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
app_1  | 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
app_1  | 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
app_1  | 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
app_1  | 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
app_1  | 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
app_1  | 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
app_1  | 	at scala.Option.foreach(Option.scala:257)
app_1  | 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
app_1  | 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
app_1  | 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
app_1  | 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
app_1  | 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
app_1  | 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
app_1  | 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925)
app_1  | 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1938)
app_1  | 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1951)
app_1  | 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1965)
app_1  | 	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
app_1  | 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
app_1  | 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
app_1  | 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
app_1  | 	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
app_1  | 	at net.sansa_stack.rdf.spark.partition.core.RdfPartitionUtilsSpark$.partitionGraphArray(RdfPartitionUtilsSpark.scala:22)
app_1  | 	at net.sansa_stack.rdf.spark.partition.core.RdfPartitionUtilsSpark$.partitionGraph(RdfPartitionUtilsSpark.scala:17)
app_1  | 	at net.sansa_stack.examples.spark.query.Sparklify$.main(Sparklify.scala:54)
app_1  | 	at net.sansa_stack.examples.spark.query.Sparklify.main(Sparklify.scala)
app_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
app_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
app_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
app_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
app_1  | 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
app_1  | 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
app_1  | 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
app_1  | 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
app_1  | 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
app_1  | Caused by: java.lang.ExceptionInInitializerError
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:27)
app_1  | 	at net.sansa_stack.rdf.spark.io.NTripleReader$$anonfun$load$1.apply(NTripleReader.scala:26)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
app_1  | 	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
app_1  | 	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
app_1  | 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
app_1  | 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
app_1  | 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
app_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
app_1  | 	at java.lang.Thread.run(Thread.java:745)
app_1  | Caused by: java.lang.NullPointerException
app_1  | 	at org.apache.jena.tdb.sys.EnvTDB.processGlobalSystemProperties(EnvTDB.java:33)
app_1  | 	at org.apache.jena.tdb.TDB.init(TDB.java:248)
app_1  | 	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
app_1  | 	at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
app_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
app_1  | 	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:163)
app_1  | 	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:109)
app_1  | 	at org.apache.jena.riot.RDFDataMgr.<clinit>(RDFDataMgr.java:81)
app_1  | 	... 14 more
app_1  | 17/05/09 13:49:32 INFO spark.SparkContext: Invoking stop() from shutdown hook
```

**Comment by LorenzBuehmann** [comment]
@earthquakesan That should have been fixed with the commit https://github.com/SANSA-Stack/SANSA-Examples/commit/b3f49ac606ca294936d8c752e6810c045fb94f83 where I adjusted the Maven shade plugin to properly package META-INF services.
